### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by fierodoug** [gmcn42/clumsyMIDI#1]
I am having a odd issue.
Everything is working but I am getting no audio out of the 3.5mm jack on the DAC, unless I touch the top row of header pins on the DAC with my finger. I almost dont have to touch it, just put my finger near it. Remove my finger and the audio goes away.
Any suggestions?
Thanx
Doug

**Comment by fierodoug** [comment]
touching a 10k ohm resistor from VIN to 3 on the DAC board gets audio working. Not sure if that is a good fix though

**Comment by gmcn42** [comment]
Hi Doug,

thanks for reporting!

Pin 3 is indeed the PCM5102's soft-mute (GND=mute, 3V3=sound on). All of the DAC boards I have here seem to have some kind of Pull-Up resistor. Pin 3 shows 3.3V when not connected and power is applied. Yours will probably show 0V. Can you check with a multimeter?

As for the fix: I recommend you DO NOT connect to VIN as this is the 5V input which goes to the board's 3.3V regulator. 5V might damage the DAC chip over time even through a 10K resistor. Instead make a connection between pin 3 and pin 5 of the DAC board. Pin 5 is the board's internal 3.3V supply. You can just add a piece of bent wire clipping below the board, a resistor should not be needed.

Please let me know if that helps. If yes, I'll add it to the instructions for now and make a Rev. 1.2 with the 3-5 connection.

**Comment by gmcn42** [comment]
I also just remembered, the DAC board should have solder bridges for pull-up or down on the bottom side (my boards are all soldered on so I couldn't see them just now :D). The one marked "3" should be in the "H" position then the board should -- theoretically -- unmute without external connections.

![solderbridge](https://user-images.githubusercontent.com/3235799/102461506-c14ffd80-4048-11eb-82b3-6920472fc02f.jpg)

The fix with the 3-5 connection should still be fine but resoldering the bridges on the DAC board might be the cleaner solution if you can do it.

**Comment by gmcn42** [comment]
Okay, 3rd post, sorry about that. I just checked another board I found lying around. It is correctly solder-bridged as in the picture above. But the thing I noticed: The solder bridges seem to be a hard connection (0Ohms) to either GND or 3V3.

If yours can be overridden (and with a 10K resistor at that) this makes me think there is either no solder bridge at all or the solder joint is broken.

Another thing this would mean: If my hard-connected DAC board would be bridged 3-L, it would be permanently muted without possibility to externally unmute (and also risking a short-circuit) which is a design decision I do not fully understand right now...

**Comment by fierodoug** [comment]
My board is soldered in so I could not check the jumpers. Pin 3 has 0 volts
using a jumper between pins 3 and 5 did the trick, working great now
Thanx

**Comment by gmcn42** [comment]
Okay, great! So the "3" bridge on your board indeed did not have a connection. Would be interesting to know how many this affects.
Anyone who reads this and has a board which deviates from the picture, let me know!

If you have any other weirdness occuring, you _might_ need to tie pins 1,2,4 to GND. I am thinking that if one bridge is unsoldered, others might be, too. But you should check the connections with a multimeter before (see https://github.com/dwhinham/mt32-pi/discussions/46) to not short-circuit anything.

**Here is an important note for everyone:** This works for @fierodoug because the solder bridge on his DAC did not have a connection to either "H" or "L" for some reason. If yours is connected to "L" and you apply the 3-5 fix, you'll effectively short the 3.3V regulator and probably fry your board. The reason is that the bridges are direct (0Ω) connections and not via a resistor.
In the above case a direct "L" connection could be effectively ruled out due to a 10K resistor being able to pull the pin high which would not be possible with a low-resistance connection acting against it.

This is why I have decided to leave the PCB as-is and add a note to the assembly instructions to inspect the DAC's solder-bridges before soldering it down (see also: https://raspberrypi.stackexchange.com/a/94951). It is the most simple and definitely the safest option.

Thanks for bringing this to my attention!

**Comment by gmcn42** [comment]
Have added the README notes in https://github.com/gmcn42/clumsyMIDI/commit/45f0cd28b3406055cf1820e843b63580c1329eb9

**Comment by dwhinham** [comment]
A user encountered the same problem when using this module via wire connection, so I've created a new wiki page over at mt32-pi too to address this: https://github.com/dwhinham/mt32-pi/wiki/GY-PCM5102-DAC-module

Thanks for figuring this out! 🙂

**Comment by Joshfindit** [comment]
Adding for anyone in future: the board I got had small bits of metal across the pads instead of a solder blob.

It's conceivable that they could get knocked off and cause this issue

![S0212dca774134de4a9da1f16972ab741d](https://user-images.githubusercontent.com/1937155/193961460-5bb8659a-e3df-41b7-9939-a10459792250.jpg)

*This photo is from the seller's listing. They look like solder, but when I took them off they were definitely metal.*
